name: ci_tests

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    name: run_tests
    runs-on: ubuntu-latest

    steps:
      - name: checkout_code
        uses: actions/checkout/@v4

      - name: setup_python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: install_dependencies
        run: pip install -r requirements.txt

      - name: run_pytest
        run: python -m pytest

      - name: run_qaqc_single_station
        run: echo 0 | python qaqc_single_station.py
